Models/User/UserRolesViewModel.cs
namespace KetNoiDB.Models.User
{
    public class UserRolesVM

    {

        public string UserId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string UserName { get; set; }

        public string Email { get; set; }

        public IEnumerable<string> Roles { get; set; }

    }
}

Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;


namespace KetNoiDB.Controllers

{

    public class RoleManagerController : Controller

    {

        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleManagerController(RoleManager<IdentityRole> roleManager)

        {

            _roleManager = roleManager;

        }

        public async Task<IActionResult> Index()

        {

            var roles = await _roleManager.Roles.ToListAsync();

            return View(roles);

        }

        [HttpPost]

        public async Task<IActionResult> AddRole(string roleName)

        {

            if (roleName != null)

            {

                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));

            }

            return RedirectToAction("Index");

        }

    }

}

Controllers/StudentController.cs
using KetNoiDB.Data;
using KetNoiDB.Models;
using KetNoiDB.Models.Domain;
using KetNoiDB.Models.Repository;
using KetNoiDB.Models.ViewModels;
using KetNoiDB.Models.Repository;
using KetNoiDB.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using Microsoft.AspNetCore.Authorization;

namespace KetNoiDB.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private IStudentRepository _studentRepository;

        public StudentController(IStudentRepository studentRepository)
        {
            this._studentRepository = studentRepository;
        }

        // GET: /Student/GetAll
        [Route("/Student/GetAll")]
        public IActionResult GetAll(string? searchString, string? type)
        {
            var allStudent = _studentRepository.GetAll(searchString, type);
            return View(allStudent);
        }

        // GET: /Student/GetStudentById/id
        public IActionResult GetStudentById(int id)
        {
            var studentById = _studentRepository.GetStudentsById(id);
            if (studentById != null)
                return View(studentById);
            else
                return View("NotFound");
        }
        [Authorize(Roles = "Admin,Editor")]
        // GET: /Student/EditStudentById/id
        [HttpGet]
        public IActionResult EditStudentById(int id)
        {
            var studentVM = _studentRepository.GetStudentsById(id);
            if (studentVM != null)
                return View(studentVM);
            else
                return View("NotFound");
        }
        [Authorize(Roles = "Admin,Editor")]
        // POST: /Student/EditStudentById/id
        [HttpPost]
        public IActionResult EditStudentById([FromRoute] int id, VMStudent student)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var studentById = _studentRepository.GetStudentsById(id);
                    if (studentById != null)
                    {
                        _studentRepository.UpdateStudentById(id, student);
                        TempData["successMessage"] = "Successful";
                        return RedirectToAction("GetAll");
                    }
                    else
                    {
                        return View("NotFound");
                    }
                }
                else
                {
                    TempData["errorMessage"] = "Data is not valid";
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
        [Authorize(Roles = "Admin,Editor")]
        // GET: /Student/AddStudent
        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }
        [Authorize(Roles = "Admin,Editor")]
        // POST: /Student/AddStudent
        [HttpPost]
        public IActionResult AddStudent(VMStudent studentData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _studentRepository.AddStudent(studentData);
                    TempData["successMessage"] = "Successful";
                    return RedirectToAction("GetAll");
                }
                else
                {
                    TempData["errorMessage"] = "Data is not valid";
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
        [Authorize(Roles = "Admin,Editor")]
        // GET: /Student/DelStudentById/id
        public IActionResult DelStudentById(int id)
        {
            var studentById = _studentRepository.GetStudentsById(id);
            if (studentById != null)
            {
                _studentRepository.DeleteStudentById(id);
                TempData["successMessage"] = "Deleted";
                return RedirectToAction("GetAll");
            }
            else
            {
                return View("NotFound");
            }
        }
    }
}

Controllers/UserRolesController.cs
using Example.Models.User;
using KetNoiDB.Models.User;
using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;


namespace Example.Controllers

{
    public class UserRolesController : Controller

    {

        private readonly UserManager<User> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public UserRolesController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)

        {

            _roleManager = roleManager;

            _userManager = userManager;

        }

        public async Task<IActionResult> Index()

        {

            var users = await _userManager.Users.ToListAsync();

            var userRolesViewModel = new List<UserRolesVM>();

            foreach (User user in users)

            {

                var thisViewModel = new UserRolesVM();

                thisViewModel.UserId = user.Id;

                thisViewModel.Email = user.Email;

                thisViewModel.FirstName = user.FirstName;

                thisViewModel.LastName = user.LastName;

                thisViewModel.Roles = await GetUserRoles(user);

                userRolesViewModel.Add(thisViewModel);

            }

            return View(userRolesViewModel);

        }

        private async Task<List<string>> GetUserRoles(User user)

        {

            return new List<string>(await _userManager.GetRolesAsync(user));

        }
        public async Task<IActionResult> Manage(string userId)

        {

            ViewBag.userId = userId;

            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)

            {

                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";

                return View("NotFound");

            }

            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesVM>();

            foreach (var role in _roleManager.Roles)

            {

                var userRolesViewModel = new ManageUserRolesVM

                {

                    RoleId = role.Id,

                    RoleName = role.Name

                };

                if (await _userManager.IsInRoleAsync(user, role.Name))

                {

                    userRolesViewModel.Selected = true;

                }

                else

                {

                    userRolesViewModel.Selected = false;

                }

                model.Add(userRolesViewModel);

            }

            return View(model);
        }
        [HttpPost]

        public async Task<IActionResult> Manage(List<ManageUserRolesVM> model, string userId)

        {

            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)

            {

                return View();

            }

            var roles = await _userManager.GetRolesAsync(user);

            var result = await _userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)

            {

                ModelState.AddModelError("", "Cannot remove user existing roles");

                return View(model);

            }

            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));

            if (!result.Succeeded)

            {

                ModelState.AddModelError("", "Cannot add selected roles to user");

                return View(model);

            }

            return RedirectToAction("Index");
        }
    }
}

Views/AddStudent_View.cshtml
@model KetNoiDB.Models.Domain.Student

@{
    var errorMessage = TempData["errorMessage"]?.ToString();
}

@if (!string.IsNullOrWhiteSpace(errorMessage))
{
   @errorMessage;
}

<form asp-controller="Student" asp-action="AddStudent" method="post">
    <div class="form-group">
        <label class="form-label">Name:</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Birth:</label>
        <input asp-for="Birth" type="date" class="form-control" />
        <span asp-validation-for="Birth" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Mssv:</label>
        <input asp-for="Mssv" class="form-control" />
        <span asp-validation-for="Mssv" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Description:</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Giới tính:</label><br />
        <input type="radio" asp-for="Gender" value="true" /> <label>Nam</label>
        <input type="radio" asp-for="Gender" value="false" /> <label>Nữ</label>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Image URL:</label>
        <input asp-for="ImgUrl" class="form-control" />
        <span asp-validation-for="ImgUrl" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
</form>

Views/EditStudentById_View.cshtml
@model KetNoiDB.Models.ViewModels.VMStudent;

@{
    var errorMessage = TempData["errorMessage"]?.ToString();
}

<h3>Chỉnh sửa thông tin sinh viên:</h3>

@if (!string.IsNullOrWhiteSpace(errorMessage))
{
    @errorMessage;
}

<form asp-controller="Student" asp-action="EditStudentById" method="post">

    <div class="form-group">
        <label class="form-label">Tên:</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Ngày sinh:</label>
        <input asp-for="Birth" class="form-control" type="date" />
        <span asp-validation-for="Birth" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">MSSV:</label>
        <input asp-for="Mssv" class="form-control" />
        <span asp-validation-for="Mssv" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Giới tính:</label>
        @Html.RadioButton("Gender", "male") <label for="male">Male</label>
        @Html.RadioButton("Gender", "female") <label for="female">Female</label>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Mô tả:</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Image:</label>
        <input asp-for="ImgUrl" class="form-control" />
        <span asp-validation-for="ImgUrl" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Finish" class="btn btn-primary" />
    </div>

</form>

Views/GetAll_View.cshtml
@model IEnumerable<KetNoiDB.Models.Domain.Student>

@{

    var i = 1;

    var successMessage = TempData["successMessage"]?.ToString();

    var errorMessage = TempData["errorMessage"]?.ToString();

}

@if (!string.IsNullOrWhiteSpace(successMessage))
{

    @successMessage

}

else @if (!string.IsNullOrWhiteSpace(errorMessage))

{

    @errorMessage

}

<h1>DANH SÁCH SINH VIÊN K19</h1>
@using (Html.BeginForm())
{
    <p>
        Tìm kiếm: @Html.TextBox("SearchString")
        @Html.RadioButton("type", "Name") Theo tên
        @Html.RadioButton("type", "Mssv") Theo mã SV
        <input type="submit" value="Tìm kiếm" />
    </p>
}

<table class="table">

    <tr class="text-center">

        <th>STT</th>

        <th>MSSV</th>

        <th>Name</th>

        <th>Birth</th>

        <th>Giới tính</th>

        <th>Hình ảnh</th>

        <th>MSSV</th>

        <th>Chi tiết</th>

        <th>Chỉnh sửa</th>

        <th>Xóa</th>

    </tr>

    @foreach (var item in Model)

    {

        <tr class="text-center">

            <td> @i</td>

            <td> @item.Mssv</td>

            <td> @item.Name</td>

            <td> @item.Birth.ToString("dd/MM/yyyy")</td>

            @if (@item.Gender == false)

            {

                <td>Nữ</td>
            }

            else

            {

                <td>Nam</td>

            }

            <td><img src="@item.ImgUrl " height="100"></td>

            <td> @item.Mssv</td>

            <td><a class="btn btn-primary" href="~/Student/GetStudentById/@item.Id">Chi tiết</a></td>

            <td><a class="btn btn-primary" href="~/Student/EditStudentById/@item.Id">Chỉnh sửa</a></td>

            <td><a class="btn btn-danger" href="~/Student/DelStudentById/@item.Id">Xóa</a></td>

        </tr>

        i++;


    }


</table>

<a class="btn btn-primary" href="~/Student/AddStudent">Add</a>

Views/GetStudentById_View.cshtml
@model KetNoiDB.Models.Domain.Student
<a class="btn btn-primary" asp-controller="Student" asp-action="GetAll">
    <i class="fa-solid fa-arrow-left-long"></i> Trở về
</a>

<h1>Thông tin mô tả sinh viên</h1>

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <img src="@Model.ImgUrl" class="img-thumbnail float-left" />
        </div>
        <div class="col-sm-9">
            <p><span class="d-inline-block w-100 fw-bold">Họ tên:</span> @Model.Name</p>
            <p><span class="d-inline-block w-100 fw-bold">Mã số SV:</span> @Model.Mssv</p>
            <p><span class="d-inline-block w-100 fw-bold">Ngày sinh:</span> @Model.Birth.ToString("dd/MM/yyyy")</p>
            <p>
                <span class="d-inline-block w-100 fw-bold">Giới tính:</span>
                @if (Model.Gender == true)
                {
                    <span>Nam</span>
                }
                else
                {
                    <span>Nữ</span>
                }
            </p>
            <p><span class="d-inline-block w-100 fw-bold">Mô tả:</span> @Model.Description</p>

            <a class="btn btn-primary" href="/Student/EditStudentById/@Model.Id">Chỉnh sửa</a>
            <a class="btn btn-danger" href="/Student/DelStudentById/@Model.Id">Xóa</a>
        </div>
    </div>
</div>

Views/Manage.cshtml
@model List<KetNoiDB.Models.User.ManageUserRolesViewModel>

@{

ViewData["Title"] = "Manage";

Layout = "~/Views/Shared/_Layout.cshtml";

}

<form method="post">

<div class="card">

<div class="card-header">

<h2>Manage User Roles</h2>
            Add/Remove Roles for User / @ViewBag.UserName.

        </div>

        <div class="card-body">

            @for (int i = 0; i < Model.Count; i++)

            {

                <div class="form-check m-1">

                    <input type="hidden" asp-for="@Model[i].RoleId" />

                    <input type="hidden" asp-for="@Model[i].RoleName" />

                    <input asp-for="@Model[i].Selected" class="form-check-input" />

                    <label class="form-check-label" asp-for="@Model[i].Selected">

                        @Model[i].RoleName

                    </label>

                </div>

            }

            <div asp-validation-summary="All" class="text-danger"></div>

        </div>

        <div class="card-footer">

            <input type="submit" value="Update" class="btn btn-primary"
                   style="width:auto" />

            <a asp-action="Index" class="btn btn-primary" style="width:auto">Cancel</a>

        </div>

    </div>

</form>

Views/RoleManager.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>

@{

    ViewData["Title"] = "Role Manager";

    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>Role Manager</h1>

<form method="post" asp-action="AddRole" asp-controller="RoleManager">

    <div class="input-group">

        <input name="roleName" class="form-control w-25">

        <span class="input-group-btn">

            <button class="btn btn-info">Add New Role</button>

        </span>

    </div>

</form>

<table class="table table-striped">

    <thead>

        <tr>
            <th>Id</th>

            <th>Role</th>

        </tr>

    </thead>

    <tbody>

        @foreach (var role in Model)

        {

            <tr>

                <td>@role.Id</td>

                <td>@role.Name</td>

            </tr>

        }

    </tbody>

</table>

Views/UserRoles.cshtml
@using KetNoiDB.Models
@model List<KetNoiDB.Models.User.UserRolesVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>User Roles</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.FirstName</td>
                <td>@user.LastName</td>
                <td>@user.Email</td>
                <td>@string.Join(" , ", user.Roles.ToList())</td>
                <td>
                    <a class="btn btn-primary"
                       asp-controller="UserRoles"
                       asp-action="Manage"
                       asp-route-userId="@user.UserId">
                        Manage Roles
                    </a>
                </td>
            </tr>
           }
    </tbody>
</table>